replicaCount: 1
deploymentStrategy: {}

image:
  repository: ricoberger/vault-secrets-operator
  tag: 1.16.5
  pullPolicy: IfNotPresent
  volumeMounts: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

args:
  - -leader-elect

environmentVars: []

vault:
  address: http://vault:8200
  authMethod: kubernetes
  kubernetesPath: auth/kubernetes
  kubernetesRole: vault-secrets-operator

rbac:
  create: true
  createrole: true
  namespaced: false

serviceAccount:
  create: true
  name: vault-secrets-operator

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

testPodAnnotations: {}

testPodLabels: {}

resources: {}

volumes: []

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitor:
  enabled: false
  labels: {}
  interval: 10s
  scrapeTimeout: 10s
  honorLabels: true
  relabelings: []


tests:
  busybox:
    image:
      repository: busybox
      tag: latest