apiService:
  ## Specifies whether the v1beta1.metrics.k8s.io API service should be created
  ## This should not be necessary in k8s version >= 1.8, but depends on vendors and cloud providers.
  ##
  create: true

## Extra arguments to pass to the metrics-server
## ref: https://github.com/kubernetes-incubator/metrics-server/blob/master/README.md#flags

extraArgs:
  kubelet-insecure-tls: true
  kubelet-preferred-address-types: InternalIP
